const Newsletter = require('./newsletter.schema');
const User = require('../user/user.schema');
const Subscriber = require('../subscriber/subscriber.schema');
const openaiService = require('../../services/openaiService');
const { sendTransactional } = require('../../services/emailService');
const logger = require('../../utils/logger');

const FRONTEND_URL = process.env.FRONTEND_URL || 'https://trustificate.clicktory.in';
const BACKEND_URL = process.env.BACKEND_URL || 'http://localhost:3000';
const BATCH_SIZE = 50;

/**
 * Polish a raw draft using the OpenAI service.
 * @param {string} draft - Raw text to refine
 * @returns {Promise<string>} Polished text
 */
const polishDraft = async (draft) => {
  return openaiService.polishNewsletter(draft);
};

/**
 * Send a newsletter to all subscribed users + confirmed external subscribers.
 * Deduplicates by email (User takes priority). Dispatches in batches.
 */
const sendNewsletter = async (subject, body, adminId) => {
  try {
    // 1. Query both collections in parallel
    const [users, subscribers] = await Promise.all([
      User.find({ newsletterSubscribed: true, isActive: true }).select('_id email'),
      Subscriber.find({ isConfirmed: true }).select('email'),
    ]);

    // 2. Deduplicate by email — User takes priority
    const userEmails = new Set(users.map((u) => u.email.toLowerCase()));
    const uniqueSubscribers = subscribers.filter(
      (s) => !userEmails.has(s.email.toLowerCase())
    );

    // 3. Build recipient list with per-type unsubscribe links
    const allRecipients = [
      ...users.map((u) => ({
        email: u.email,
        unsubscribeLink: `${FRONTEND_URL}/unsubscribe/${u._id}`,
      })),
      ...uniqueSubscribers.map((s) => ({
        email: s.email,
        unsubscribeLink: `${BACKEND_URL}/api/public/newsletter/unsubscribe/${encodeURIComponent(s.email)}`,
      })),
    ];

    const recipientCount = allRecipients.length;

    // 4. Batch dispatch with Promise.allSettled
    for (let i = 0; i < allRecipients.length; i += BATCH_SIZE) {
      const batch = allRecipients.slice(i, i + BATCH_SIZE);
      await Promise.allSettled(
        batch.map((recipient) =>
          sendTransactional(
            recipient.email,
            'newsletter-broadcast',
            { subject, body, unsubscribeLink: recipient.unsubscribeLink },
            subject
          )
        )
      );
    }

    // 5. Persist newsletter record (slug auto-generated by pre-save hook)
    await Newsletter.create({
      subject,
      body,
      sentBy: adminId,
      recipientCount,
    });
  } catch (err) {
    logger.error('Newsletter send failed:', err);
  }
};

/**
 * Return all newsletter records sorted by sentAt descending, with sender info populated.
 * @returns {Promise<Newsletter[]>}
 */
const getHistory = async () => {
  return Newsletter.find()
    .sort({ sentAt: -1 })
    .populate('sentBy', 'displayName email');
};

module.exports = {
  polishDraft,
  sendNewsletter,
  getHistory,
};
